# Generated by Django 3.1.2 on 2021-01-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='usuer',
            new_name='user',
        ),
    ]
